# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-18 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=100, verbose_name='PushAll ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date subscribe')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'ordering': ['-date'],
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
